language: node_js
node_js:
- '4.1'
install:
- npm install -g elm
cache:
  directories:
  - elm-stuff/packages
  - elm-stuff/build-artifacts
script: bash ./deploy.sh
env:
  global:
    secure: n0EMeY/yo+vqXI9ahEw6wwlNsLNRMGZtCv5H2z/4qfmdvB1Hqm0BZ5RhKi4hi2gTWxL/1kSk+eZuMe+PkS1W7tIqdfrMkHZztg024uweukcXUI4vibFTNghv5t58ZdMtMsx6TdmbuPf2I2HLZN/ClHWp0WCsfygVpsc8NLhgXyAATfUeyO5zcwXFd7yirc4JHBJTjAckhW26YubsoPnqmt2Kuf61gsteCHIdrB6tDgeSTWgnDtK9vUzMZeuT9Wc8cXrKOZWcMjbJlHoYfWNdADle4yw7y5kWaIhBFYUI4hU5cDpuaz/zXlZYA4QfaC3HbzBUk+7XrjK0LcSLO/a854iuZHubJ2tuHPUy48l7ImZZOtDDkXwswtjLOcSgFUBz19sxG3ReWjFRnVrRxlWw7SSel9WRSKqJI2i6wPgzP2juMi7Zj3GNb7DpUJpmlt++KC3dvixqM5e0n7I8BaY4R3pNw0HB91Pubtsj0vancVUbIr4Ccs+OAUidIaVZ8Utx7osYdzHQdszhbv3CST8zq5HgPCL+dlYPjtrf4dvwmC2IcUKEuUbPpWv87HgMaefpVsLh1SepFkIF2dy4TS+3YFtBV3fqaVDT/dtQTfYpvMQwDg9wq3kL8InqzkR9T6VdBFTd/K6q7epbSiUSO3UAIjNfwYD0hlTr4yKBCVXgUzI=
